### ISSUE TITLE
Display of search above map info panel (smartphones)

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#105]
The info panel for maps (when viewed on a smartphone) has the map search widget displayed at the top. It would make more sense to display the map name here, as the map name is not visible anywhere else in the map view and there is nothing to search in the current view.

**Comment by allisonmuise** [comment]
Implement with Option 1 from above

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will implement option 1 and include the changes in next release.

**Comment by allisonmuise** [comment]
verified
