### ISSUE TITLE
Unable to open web mapping application in iOS7

### ISSUE THREAD

**Issue by HeatherEisan** [Esri/map-and-app-gallery-template#150]
Repo steps

1. Open Map and App Gallery application.
2. Tap on a Web Mapping Application template.
3. A new about:blank tab opens, but the application doesn't load.

Work around

1. Open Map and App Gallery application.
2. Tap on a Web Mapping Application template.
3. A new about:blank tab opens, but the application doesn't load.
4. Tap on the Map and App Gallery tab, then the application loads.

**Comment by allisonmuise** [comment]
small use case. iOS8 is >75% adoption
