### ISSUE TITLE
return to full gallery when search box cleared

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#154]
Clearing the search box of all values with the delete or backspace keys should have the same behavior as clickign the 'x' in the search box - the gallery should return to showing all items.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise: We will implement the same functionality as provided on the click of 'x' button in search box. We will include this in next release.

**Comment by allisonmuise** [comment]
verified
