### ISSUE TITLE
Only public items visible in Chrome and IE9

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#155]
1) Create app from group with mixed public and private content
2) load app - all public items visible and private items hidden as expected
3) Sign in to app - still only public items visible

This is reproducible in IE9 and Chrome, but not FireFox or IE11

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @LindsayThomas, @ScottOppmann, 
We were able to reproduce this issue, though it did occur randomly in Firefox and IE11 too.
We narrowed this down to a timing issue in the asynchronous calls to sign-in and the app gets the token and uses it further. Sometimes, the app proceeds further without propagating the token to subsequent calls even after sign in.
We were able to fix this by making the sign-in synchronous to ensure the identity is correctly propagated further into the app. 
We will include this fix in the upcoming release.

**Comment by allisonmuise** [comment]
verified
