### ISSUE TITLE
adjust grid spacing

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#156]
Please correct the spacing of the grid tiles so that:

- when re-sizing the browser window, the tile on the right does not wrap to the next line until the edge of the graphic is aligned with the right edge of the sign in/out graphic
- the tiles jump up to fill the space in the row above as soon as there is space.

Currently this is the minimum white space possible before the graphic wraps. I should be able to narrow it until the thumbnail aligns with the sign in/out graphic.
![minspace](https://cloud.githubusercontent.com/assets/2752195/6696440/a787327c-cca6-11e4-9e1c-4dabb67d8fb3.png)

Currently the browser can be resized this far without adding a new item to the end of the row. The next thumbnail should jump up as soon as there is enough space for it between the previous thumbnail and the edge of the sign in/out graphic
![maxspace](https://cloud.githubusercontent.com/assets/2752195/6696439/a60eb12c-cca6-11e4-95ad-5b910af09125.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will implement this and include it in the next release.

**Comment by allisonmuise** [comment]
verified
