### ISSUE TITLE
Gallery items do not open when configured basemap group is not found in Org/portal 

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/map-and-app-gallery-template#157]
@allisonmuise,
We have observed an issue during our testing that when a basemap group (owner and title) is configured, 
* If basemap group is configured (owner and title), the app tries to find the group in the Org/portal. If it does not find the basemap group, then as a fallback, the app tries to search the group in 'arcgis.com', by setting 'arcgisUtils.arcgisUrl' to 'www.arcgis.com'. 
  * A side effect of this is, the gallery loads up, but when we try to view an item, it tries to locate all items in 'www.arcgis.com' instead of the Org/Portal and displays an error message 'Item does not exist or is inaccessible'. 
  * When template is AGOL hosted, public items work fine, but users cannot open private items even after signing-in. 
  * When app is portal hosted, public items also do not open, because the app tries to locate items in 'arcgis.com'. 
* If no basemap group is configured, then the Org's basemap group is used

Our approach to fix this, is to:
Don't try to find the basemap group in arcgis.com, instead use the Org/Portal's basemap group as the fallback. This is the same as when no basemap group is configured.

**Comment by allisonmuise** [comment]
Please proceed with this approach

**Comment by allisonmuise** [comment]
verified
