### ISSUE TITLE
Description box overflows bottom of display window

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/map-and-app-gallery-template#159]
If the description is longer than can fit into the display window--say 5 paragraphs of lipsum.com--then the description is displayed in a box that isn't constrained to the bottom of the display window. As a result, one cannot see the bottom of the scrollbar nor the "Less" button.  Occurs in QA version.

![image](https://cloud.githubusercontent.com/assets/2125181/8414814/50535c60-1e4f-11e5-9da4-0b869a813ba0.png)

**Comment by skrishn** [comment]
Issue is not reproducible in production.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Please submit a pull request with a fix for this issue ASAP.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We were able to fix this by adding one line in gallery.js after line number 129
`domAttr.set(query(".esriCTExpand")[0], "innerHTML", nls.expandGroupDescText);`
Now the app displays 'more' and 'less' buttons appropriately.
