### ISSUE TITLE
Description box resized without updating "More"/"Less" tag

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/map-and-app-gallery-template#160]
If one resizes the display window while the description is expanded, the description collapses. But since this is done in a different part of the code than the part that handles the "More" & "Less" tag updates, the tag is not updated to match the new description expanded state. Occurs in the QA version. Workaround is to click "Less" to re-expand the description and then resize the display window again.

![image](https://cloud.githubusercontent.com/assets/2125181/8414877/a06dea08-1e4f-11e5-8de3-2aad6596a30b.png)

**Comment by skrishn** [comment]
This occurs in production

**Comment by allisonmuise** [comment]
@skrishn : Thanks for checking - we'll push this fix to next release.
