### ISSUE TITLE
accessibility support - keyboard navigation

### ISSUE THREAD

**Issue by darkbluemsu** [Esri/map-and-app-gallery-template#164]
I understand ESRI has limited support with accessibility due to nature of GIS mapping software. But this map gallery is NOT really a GIS mapping application. It would be nice to give users ability to be able to to use keyboard to tab through this application.

**Comment by allisonmuise** [comment]
This is a fair point, and something we will take into consideration in future development work on this app.

**Comment by allisonmuise** [comment]
duplicate #197
