### ISSUE TITLE
Improve UI for returning to gallery from the map viewer

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#166]
see email from Matt D 9/10/15 re: user confusion about how to return to gallery from map viewer. Clicking the Gallery name is not intuitive.

I will work with the design team to spec up a visual indicator for this action.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Here are two options to go back to gallery 

### Option 1
![image](https://cloud.githubusercontent.com/assets/2959186/12505069/811f43b0-c109-11e5-9380-c2225ea9fe98.png)
![image](https://cloud.githubusercontent.com/assets/2959186/12505076/90669bca-c109-11e5-86de-df56169f7c05.png)

------
### Option 2

![image](https://cloud.githubusercontent.com/assets/2959186/12505088/ba813a50-c109-11e5-8ad0-1dadc2c2ab37.png)

![image](https://cloud.githubusercontent.com/assets/2959186/12505191/99f7a05c-c10a-11e5-8a94-abbe61cff984.png)

**Comment by allisonmuise** [comment]
@ScottOppmann @LindsayThomas @NikkiGolding 
What do you guys think?

**Comment by NikkiGolding** [comment]
@allisonmuise I like option 2 except the placement of the back option on the 'item view' last image above.

**Comment by ScottOppmann** [comment]
@allisonmuise - I like option 2 as well.  Think we should style the "back" button to match other buttons on that page.  Take a look at the "view" button for reference.  Should the button really be at the bottom of the page? Seems odd to have a back button on the UI before you've even had a chance to review the content on the page.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @ScottOppmann, @NikkiGolding 

How about this? The back button is styled similar to "View" button. If we put the back button at the bottom of the page, then it wont be visible on smartphones unless users scroll down.

![image](https://cloud.githubusercontent.com/assets/2959186/12549308/7ffd3f3e-c382-11e5-9d58-e4f3ca4f82b6.png)
![image](https://cloud.githubusercontent.com/assets/2959186/12549320/96bfac34-c382-11e5-8d4b-f6bdee1bcbb0.png)

**Comment by ScottOppmann** [comment]
@allisonmuise - I like this much better.

**Comment by LindsayThomas** [comment]
@allisonmuise agreed

**Comment by allisonmuise** [comment]
I like it, too.
@CTLocalGovTeam let's go with this latest option.

**Comment by allisonmuise** [comment]
verified
