### ISSUE TITLE
Improve UI for opening the item vs the item details

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#167]
See Matt's email 9/10/15

There is user confusion over accessing the details panel vs opening the item. There is no visual indication that there are two options available depending on what is clicked in the item UI

Suggestion is title and thumbnail go to the item, with 'Details' link to the item info. I will work with the design team to design an addition to the UI for accessing the details vs accessing the item.

**Comment by allisonmuise** [comment]
There is user confusion over accessing the details panel vs opening the item. There is no visual indication that there are two options available depending on what is clicked int he item UI.

**Comment by allisonmuise** [comment]
Updated Desktop/list view UI:
Ideally we'd like to use pictorial buttons instead of the words Open and Details. The Details graphic should match what is chosen for the other views.
![suggested_list](https://cloud.githubusercontent.com/assets/2752195/12861631/aec06e1e-cc19-11e5-978a-f9e0b04c78e5.png)

**Comment by allisonmuise** [comment]
Updated Desktop/Grid view:
Clicking the details button (i button) should open the details page. Details button graphic should be consistent across all scenarios.
Clicking the thumbnail or the title should open the item.
Is it possible to wrap the item title to 2 lines?
![suggested_grid](https://cloud.githubusercontent.com/assets/2752195/12861743/71737f64-cc1a-11e5-8764-e22b27d7044a.png)

**Comment by allisonmuise** [comment]
Update smartphone view:
Currently, smartphones load the app in List view. Is it possible to load them using the Grid view so that the thumbnails and title are the focus rather than the summary with a tiny thumbnail? If this is a significant development effort, let me know. 
All grid view comments above apply here as well.

![suggested_phone](https://cloud.githubusercontent.com/assets/2752195/12861801/d6f8c59c-cc1a-11e5-82e8-23ff35a79d7b.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,
UI Changes-

1. Updated Desktop/list view UI:-Clicking the thumbnail or the title should open the item as well as clicking the Open button -  _We will implement this._

2. Updated Desktop/Grid view:-
  a. Clicking the details button (i button) should open the details page- _We will implement this._
  b. Clicking the thumbnail or the title should open the item- _We will implement this._
  c. Is it possible to wrap the item title to 2 lines?- _We can show the item title in two lines but if  the title is longer than two lines then ellipsis will not be shown. Please confirm._

3. Update smartphone view- _It was not supported yet but can be implemented. It requires 2-3 days efforts._

**Comment by allisonmuise** [comment]
@ScottOppmann : Are you ok with wrapping the title to two lines, even if the ellipsis can't be shown?

**Comment by ScottOppmann** [comment]
@allisonmuise - wrapping should be fine.  I think the "i" near the map/app title is going to be very difficult to navigate on the smartphone unless we make it the same size as the "i" in the title bar.  is there another way to address this need?  Could the title open the details the thumbnail open the map?

**Comment by allisonmuise** [comment]
@ScottOppmann : The 'two ways to open' is what we are trying to change. I've heard overwhelmingly from internal and external users that this is not the behavior they expect. We should be able to make the button to the item details the same size as the button to the app details. The mockups were the best I could do in Snagit :)

@CTLocalGovTeam : Please wrap the titles to two lines in smartphone mode, and make the button to the item details the same size as the button to the app details. This button can be restyled as necessary to fit with the rest of the app UI.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
Here is a mockup of the open and details buttons as icons instead of text buttons. Please let us know what you think.

![image](https://cloud.githubusercontent.com/assets/2959186/13076928/94c0dcf4-d4db-11e5-865b-735e323ddea0.png)

![image](https://cloud.githubusercontent.com/assets/2959186/13077159/1f68d59a-d4dd-11e5-9b33-9c53e2754168.png)

![image](https://cloud.githubusercontent.com/assets/2959186/13076935/a0917b42-d4db-11e5-94c7-00b91666ceff.png)

![image](https://cloud.githubusercontent.com/assets/2959186/13076937/aaea1ff4-d4db-11e5-8ab8-2f8a256b389c.png)

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

Here is a mockup of the suggested changes with a different theme color. Please let us know if this is ok. Please click the images to view full size.

![image](https://cloud.githubusercontent.com/assets/2959186/13252198/5915e6a6-da5b-11e5-89b8-afd2ed6b64c7.png)

![image](https://cloud.githubusercontent.com/assets/2959186/13252207/661620b4-da5b-11e5-8b30-d2ab7666ae6c.png)

**Comment by allisonmuise** [comment]
@ScottOppmann : I just noticed that the 'Open' button is actually the same graphic we use for 'Share' in other apps such as Site Selector. It's more of an 'open' graphic to me than a 'share', but do you have any concerns about mixed use of the same button?

**Comment by allisonmuise** [comment]
verified
