### ISSUE TITLE
Add support for new Form items

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#171]
At 3.10 (November) a new Form item type was added to support Survey 123. These items should open in Survey 123. I will add sample items to this issue once I find some.

https://devtopia.esri.com/WebGIS/arcgis-portal-app/issues/4744#issuecomment-287678

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We are unable to locate the docs for "Form" item type. Can you please point us to the documentation for this item type.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : This item type is not yet visible on PRD or documented in the public help. I should be able to give you a URL to a sample item on devext in the next few weeks. 

I believe the action will be similar to how the MAG handles Ops Dashboard - Identify if the item is being accessed on a Survey123-compatible device and if it is, identify if Survey123 is installed. If it is, open the item in that app; if it's not, prompt to install. 

Once there are items of this type on devext we'll be able to confirm that this is how they are handling opening these items.

**Comment by allisonmuise** [comment]
survey forms are now Microsoft Excel type items which will be handled with existing logic.
