### ISSUE TITLE
Add support for new Workforce item type

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#172]
At 3.10 (nov) a new Workforce Project item type was added to AGOL. These items should open in the new Workforce app. I will add a sample item once I find one.

https://devtopia.esri.com/WebGIS/arcgis-portal-app/issues/4784#issuecomment-287798

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We could not find an item type named "Workforce Project" in the list of supported items in AGOL docs. We were looking [here](https://doc.arcgis.com/en/arcgis-online/share-maps/supported-items.htm)

Workforce for ArcGIS consists of a native mobile app and a back-office web app. We see that the beta is going to start around Jan 12. 

Can you please describe the behavior you expect when user clicks on thumbnail of an item of type "Workforce Project" on desktops as well as smartphones?

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : This item type is not yet visible on PRD or documented in the public help. I should be able to give you a URL to a sample item on devext in the next few weeks. 

I believe the action will be similar to how the MAG handles Ops Dashboard - Identify if the item is being accessed on a Workforce-compatible device and if it is, identify if Workforce is installed. If it is, open the item in that app; if it's not, prompt to install. 

Once there are items of this type on devext we'll be able to confirm that this is how they are handling opening these items.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 
We are not targeting a solution for this since per Scott, *"I don’t think we need to include Workforce items in this release of the gallery. The new items will only be in beta and I don’t think they have plans to move them until May at least."* 
Can you please reassign an appropriate label/milestone for this issue.

**Comment by allisonmuise** [comment]
Per Scott's comment, I moved this issue from 4.1 to 4.2. @ScottOppmann : I think we should add support for this at 4.2. Do you agree?

**Comment by ScottOppmann** [comment]
@allisonmuise - lets just track the Workforce release and see when they plan on coming out of Beta.  I heard Q2 of 2016, but we'll have to see how this develops in the spring.

**Comment by allisonmuise** [comment]
closing this. There are better ways to access workforce projects and I don't think we should encourage people to use MAG
