### ISSUE TITLE
Item details text not wrapping correctly

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#177]
The text in the Description portion of the item details runs off the screen, even when the browser is in full-screen mode. The text should wrap with a small buffer on the right side of the the content.
cc @lindsayking

**Comment by lindsayking** [comment]
Screen grab for reference:

![mapandappgallerytextrunoff](https://cloud.githubusercontent.com/assets/4316336/11407212/3ad48e54-9366-11e5-982c-f5e700fb65a4.png)

**Comment by allisonmuise** [comment]
verified
