### ISSUE TITLE
If group has no items to display upon app startup, leftPanel references not-yet-existing div

### ISSUE THREAD

**Issue by MikeTschudi** [Esri/map-and-app-gallery-template#179]
Function _createNoDataContainer in leftPanel.js references `query(".esriCTInnerRightPanel")` twice for a domClass.replace and once to get the container for a no-results-text message. When a group has no items display upon app startup, the gallery has not yet been started, so the div with class `esriCTInnerRightPanel` doesn't yet exist and `query(".esriCTInnerRightPanel")` returns an empty list.

The beginning of the function checks for this empty list before using the first element of the list
```
if (query(".esriCTInnerRightPanel")[0]) {
    domClass.replace(query(".esriCTInnerRightPanel")[0], "displayNoneAll", "displayBlockAll");
}
```
but the second access does not, which causes a failure in the program at this point
```
if (domClass.contains(query(".esriCTInnerRightPanel")[0], "displayNone")) {
    domClass.replace(query(".esriCTNoResults")[0], "displayNoneAll", "displayBlockAll");
} else {
    domClass.replace(query(".esriCTNoResults")[0], "displayBlockAll", "displayNoneAll");
}
topic.publish("hideProgressIndicator");
```

The effects of this failure appear to be
1. the div containing the message "No results found" is created but not placed into the page
2. the "hideProgressIndicator" message is not published to hide the loading indicator (but this message is published elsewhere after the popup alert box is displayed, so this publication appears to not be needed)

Console error message:
```
TypeError: Cannot read property 'className' of null
    at Object.m.contains (http://js.arcgis.com/3.15/init.js:223:460)
    at declare._createNoDataContainer
```

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,
We are able to reproduce the issue. This is because of the function is trying to access the elements which are not created yet. This is  a low LOE and low risk fix. We can provide the fix in next week.

-Varsha

**Comment by allisonmuise** [comment]
@CTLocalGovTeam 
Varsha, that's great. Thanks!

**Comment by MikeTschudi** [comment]
Looks good; thanks!
