### ISSUE TITLE
Set font size to 14pt for item title and item type

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/map-and-app-gallery-template#184]
@allisonmuise 

Currently font size of item title and type is 
 
- Smartphone view -14px
- Desktop view- 12px

In the mockup below - Item title and item type font size is 14pt. Below are the screenshots-

##### In smartphone-  Grid view

![image](https://cloud.githubusercontent.com/assets/2959186/13984518/ba88ee2e-f11c-11e5-81d3-3205389b65c2.png)
---------------
##### In smartphone- List view

![image](https://cloud.githubusercontent.com/assets/2959186/13984581/3015132a-f11d-11e5-8b8b-e5abda00c008.png)

-------
##### In desktop(item title and item type is 14pt)- Grid view

![image](https://cloud.githubusercontent.com/assets/2959186/13984909/47a28f3e-f11f-11e5-9d9d-a892376f54c6.png)

#####  In desktop(item title and item type is 14pt)- List view

![image](https://cloud.githubusercontent.com/assets/2959186/13984768/4c3adf98-f11e-11e5-8f27-ea8b566005ab.png)

Please confirm.

**Comment by allisonmuise** [comment]
14 px for title, 12 px for item type

**Comment by allisonmuise** [comment]
verified
