### ISSUE TITLE
Open and details icon size

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/map-and-app-gallery-template#185]
@allisonmuise 

In the first image- size of both the icons is same as the font size of item title
In the second image- size of both the icons is less than the font size of item title

Below are the screenshots of open and details icon sizes-

![image](https://cloud.githubusercontent.com/assets/2959186/13986083/6693a9e4-f126-11e5-950a-d47905bab6c3.png)

Could you please confirm, which option we should use?

**Comment by allisonmuise** [comment]
I prefer 'a'

**Comment by allisonmuise** [comment]
verified
