### ISSUE TITLE
X button is missing in Tag element

### ISSUE THREAD

**Issue by skrishn** [Esri/map-and-app-gallery-template#188]
1. Create/Open a Maps and apps Gallery application in dev environment
2. Click on a Tag element. Notice there is no 'x' button.
Note: Issue is seen on all browsers. Can't be reproduced in production.

       ![image](https://cloud.githubusercontent.com/assets/3836616/15163456/6efde56a-16bd-11e6-9411-6e30df5f8205.png)

Production environment
      ![image](https://cloud.githubusercontent.com/assets/3836616/15163409/2cdb169e-16bd-11e6-839f-f471221f1381.png)

**Comment by allisonmuise** [comment]
x button restored
