### ISSUE TITLE
Feature Layer - Expose URLs and service info

### ISSUE THREAD

**Issue by MikeMillerGIS** [Esri/map-and-app-gallery-template#193]
Looking at using the Gallery for the service catalog, but a Feature Layers url is not visible
![image](https://cloud.githubusercontent.com/assets/2707285/16236332/03c0d01e-37a6-11e6-877d-f6b00b80ca7f.png)

**Comment by allisonmuise** [comment]
closing - app will be moved to mature support at 6.1. Use Minimal Gallery app instead.
