### ISSUE TITLE
Proxy issues when Running from within another Application

### ISSUE THREAD

**Issue by KCSchreiber** [Esri/map-and-app-gallery-template#198]
Hello all,

We are trying to run the Maps and Apps Viewer (MAAV) application from within our own web application. When I have run the MAAV as its own site and IFramed it into our web app, everything works as it should and all items in the group show. When I attempt to run the MAAV from within our web application, the MAAV will only load the items in the group that are publically available on ArcGIS Online.

The group is shared on AGOL with the Organization and the items that it contains vary with who they are shared with (some are public, some are org). In order to display the items in the group that are shared only with the Org, I have the app utilizing the Esri Resource proxy. As I said above, when the MAAV is hosted as its own site, everything works fine. When I host it as part of our Web Application, only the public items in the group display.

When looking at my dev tools in Chrome (while the MAAV is embedded inside our app) it hits the proxy, but still does not load all of the items in the group. 

I can't figure out why.

Thanks!

**Comment by allisonmuise** [comment]
Hi KC - 

Could you contact Esri Support Services with this? They will be able to work with you to troubleshoot and identify the issue. 

Some things are easier to work through over the phone or with a screenshare than via GitHub posts :)

Thanks!
-Allison
