### ISSUE TITLE
configuring app with oauthappid

### ISSUE THREAD

**Issue by psanyal** [Esri/map-and-app-gallery-template#199]
Hi,

I am seeing some errors on browser console with I configure the app to use "oauthappid".

Can you please share info on appid, oauthappid config parameters? Are they different values? I can find appid on registered web app on AGOL.

Thanks

**Comment by allisonmuise** [comment]
@psanyal 
Can you provide some more information about what you are trying to do? Perhaps then I can help you with the parameters you need. In general you shouldn't need any of these parameters for this app. They are part of the boilerplate the app is built on, but unnecessary for 99% of use cases. The parameters you need to configure are documented here: http://solutions.arcgis.com/local-government/help/maps-and-apps-gallery/get-started/additional-configuration/

**Comment by psanyal** [comment]
@allisonmuise

 I used this template to create an application. AGOL org Named user account works, but it does not allow Enterprise Accounts to login to the application. Its configured in the ArcGIS Organization to allow for their enterprise logins to work with ArcGIS Online. Would this template need to configured/customized to support those single sign on with enterprise accounts?

**Comment by allisonmuise** [comment]
@psanyal 
This application handles authentication differently in the two environments. I don't believe that it's currently possible to use enterprise credentials with a local version of Maps and Apps Gallery. Migrating this application to the latest boilerplate will resolve this issue. That is currently on our roadmap for mid-2017 (waiting for functionality in the 4.x API). Until then, I recommend leaving the application hosted in ArcGIS Online.

**Comment by allisonmuise** [comment]
closing this for now. It should be resolved with #205 . For now, I suggest using the application hosted in AGOL or Portal.
