### ISSUE TITLE
Is it possible to have a unique URL for each 'web map' item?

### ISSUE THREAD

**Issue by yeonkim** [Esri/map-and-app-gallery-template#200]
First, thank you so much for creating and maintaining Map and App Gallery. We have been using it for about a year, and we like it very much.
http://maps.gaithersburgmd.gov/gallery/

I have a question for 'web map' items. Right now, they are opening in the default map viewer. Is it possible to have URL parameters for individual web map items? For example, it would be really nice to directly link to each web map (with map viewer), something like
http://maps.gaithersburmd.gov/gallery/index.html?webmap=zoning

I checked with technical support a year ago, and was told that it was not one of the supported features. I checked the recent releases but it seems this feature is not on the radar. 

Please let me know if I missed it somehow. :) Any pointers or suggestions are appreciated.

**Comment by allisonmuise** [comment]
@yeonkim : you were told the correct information - this is not a currently supported function. It is on our radar, but we don't have a timeline yet for when it will be implemented.

For now, you can track development of this functionality on issue #72 . You can also log an official enhancement request with Esri Support.
