### ISSUE TITLE
Accomodate long translated text

### ISSUE THREAD

**Issue by skrishn** [Esri/map-and-app-gallery-template#201]
Noticed a messed up UI with long text (Indonesian is shown below)

![image](https://cloud.githubusercontent.com/assets/3836616/20360516/de5911bc-abe8-11e6-950d-9d4fb07612d3.png)

![image](https://cloud.githubusercontent.com/assets/3836616/20360522/e32629f0-abe8-11e6-9352-0253bc8d36c2.png)

**Comment by allisonmuise** [comment]
Search bar should slide to the left to accommodate longer text.
