### ISSUE TITLE
iOS browsers on mobile devices don't zoom to searched location!

### ISSUE THREAD

**Issue by vscott11** [Esri/map-and-app-gallery-template#202]
I have a JS template that works fine on the desktop. However on the mobile IOS system, in both Safari and Chrome, the functionality works, but the user must manually scroll to the location after entering the address. It does not zoom to the searched location.

Try this application on an iOS mobile device.
https://www.phoenix.gov/mayorcouncil/find-my-council-district
Use: 2020 W Morningside Dr, Phoenix, Az

**Comment by allisonmuise** [comment]
@vscott11 : are you experiencing this issue with the Maps and Apps Gallery application? The application in your link looks like a configuration of Basic Viewer.

**Comment by allisonmuise** [comment]
closing as this issue doesn't seem to be related to the Maps and Apps Gallery.
