### ISSUE TITLE
Implement shared theming

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#204]

**Comment by allisonmuise** [comment]
elements to show in header color:
![11-30-2016 2-13-07 pm](https://cloud.githubusercontent.com/assets/2752195/20773917/e6205fce-b708-11e6-95eb-ad2d6f2f8fb2.png)
![11-30-2016 2-19-51 pm](https://cloud.githubusercontent.com/assets/2752195/20773883/c919da72-b708-11e6-8a30-4970e386a776.png)

**Comment by allisonmuise** [comment]
the panel text color:
![11-30-2016 2-13-07 pm](https://cloud.githubusercontent.com/assets/2752195/20774041/6682b19e-b709-11e6-93c0-b62d60368f1d.png)
![11-30-2016 2-18-47 pm](https://cloud.githubusercontent.com/assets/2752195/20774040/66830446-b709-11e6-98ea-738af6791032.png)

**Comment by allisonmuise** [comment]
Don't use the shared theme parameter for the panel color.

Use the shared theme logo for the logo in the top left corner of the app.

All other rules and guidelines match work previously done in CSReporter & CSManager.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

> Don't use the shared theme parameter for the panel color.

We understand this means that the panel background remains white. And we do not alter its color by    any shared parameters. 

> the panel text color:

We understand that this means we will apply body text color from shared theme parameter to items referred.
 
Additionally, we need your inputs on the source of the color for the following elements:
![image](https://cloud.githubusercontent.com/assets/2959186/22424260/cc26f78e-e71b-11e6-9a2f-a688e8f89231.png)
![image](https://cloud.githubusercontent.com/assets/2959186/22424290/f201a314-e71b-11e6-98b6-09654d44fbc3.png)
![image](https://cloud.githubusercontent.com/assets/2959186/22424446/9f0da6c0-e71c-11e6-9249-f1636d128451.png)

--Pratik Gohil

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

As per our call, here is our understanding of color mapping:
![image](https://cloud.githubusercontent.com/assets/2959186/22466012/5b0815a0-e7e4-11e6-8c3a-b7d542e26776.png)

![image](https://cloud.githubusercontent.com/assets/2959186/22465669/cb2ddec0-e7e2-11e6-8080-d433466a3f54.png)

![image](https://cloud.githubusercontent.com/assets/2959186/22465825/9d583f6c-e7e3-11e6-8237-1b4c2927d9e7.png)

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Looks good!

**Comment by allisonmuise** [comment]
The application logic should only read the values set in the configuration panel; there is no need for the app to handle any of the logic in deciding when org theme vs default vs configured values are used. The configuration panel will handle this logic.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : For backwards compatibility, the original 'theme' property must be used for the shared theme header.background property. Please make the necessary adjustments and submit a code drop ASAP.
Please copy Suba on this PR as I will be out of the office next week.

cc @skrishn

**Comment by allisonmuise** [comment]
Likewise, the default value for this parameter must be #007ac2

**Comment by skrishn** [comment]
@CTLocalGovTeam : I removed the headerBackgroundColor property from  configpanel.js along with its references in the config panel 
When I open the app this is what I see
 
![image](https://cloud.githubusercontent.com/assets/3836616/22952524/476b7120-f2c2-11e6-977c-e51ff5c1ffc1.png)

This property is used in 38 different places across the app. 

cc @allisonmuise

**Comment by CTLocalGovTeam** [comment]
@allisonmuise, @skrishn

Removing the headerBackgroundColor property from config.js will not work as it has some dependencies in the code. To remove the headerBackgroundColor property from config.js we would need to do some code changes.

We will do the code changes and submit the pull request ASAP.

Please let us know your thoughts on this.

--Pratik Gohil

**Comment by skrishn** [comment]
@CTLocalGovTeam . Please go ahead and make the changes

Cc @allisonmuise

**Comment by skrishn** [comment]
@allisonmuise @CTLocalGovTeam verified. looks good.
