### ISSUE TITLE
No app icon if group not public

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#206]
App should be falling back to the default icon when group icon is not accessible.
App icon should draw once credentials are provided.

Per @MikeTschudi 

What I’m seeing is that the API’s esri/arcgis/utils.getItem() function behaves differently for the two apps when the app tries to fetch the group info:
•	Private/OK app:  getItem causes a token to appear in the esri/IdentityManager and the fetch succeeds
•	Public/failing app:  getItem doesn’t lead to token and the fetch returns nothing

If there isn’t a URL configured for the app’s icon, the app falls back to the group’s icon.  If there isn’t a group icon, the app falls back to its themes/images/defaultLogo.png file.  Without a token, the app can’t read the group’s information and skips the entire icon cascade, so I’d expect that even a configured icon wouldn’t appear.

A bit later in the API, the token gets initialized via the esri/IdentityManger.checkSignInStatus() call and starts getting appended to queries, so the app is able to fetch the group gallery, perhaps because the API is able to use this information internally.  But since checkSignInStatus occurs after the token is cached in a global variable, that token remains unset until the user logs in—the one other place where it gets set.

I believe that if we move the checkSignInStatus call earlier in the app—before the failing getItem—we’ll have the token when needed.

**Comment by MikeTschudi** [comment]
Suba found that, "To repro the issue you’ll have to be signed to the org in a different tab." Because of the checkSignInStatus call, the app is able to display the group contents without signing in. 

We just need to make this call earlier: from line 160 in searchAGOLGroupItems.js to before line 147; I was able to make the failing app work by using the debugger to make the checkSignInStatus call before the getItem call.

**Comment by allisonmuise** [comment]
closing - app will be moved to mature support at 6.1. Use Minimal Gallery app instead.
