### ISSUE TITLE
Sign in needs to be hit twice to get sign in to the app

### ISSUE THREAD

**Issue by skrishn** [Esri/map-and-app-gallery-template#208]
Open a Map and App gallery application.  (make sure you're not logged in to org and app is shared with everyone)
Hit sign in and enter credentials
Notice that 'Sign In' button still shows up as 'Sign In' and items aren't updated
Hit Sign in again and the items gets updated and 'Sign in' button is changed to 'Sign Out'

Noticed only in devext

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : This is a regression. Could you please include a fix for this as part of the SOW you are writing up for the theme work? We need to address this for 5.1.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

As this is an issue with devext, can you please share the app url where we can debug the issue.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam URL send via email.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : The AGOL/API teams are saying that this must be something on the app side. Please continue digging into this and send me any details.

**Comment by allisonmuise** [comment]
verified
