### ISSUE TITLE
Search bar border color 

### ISSUE THREAD

**Issue by skrishn** [Esri/map-and-app-gallery-template#212]
Open the app

Click on the search bar - the border color shows around the search text area but not on search button which looks funny.

![image](https://cloud.githubusercontent.com/assets/3836616/23191840/c3e32b84-f854-11e6-9cba-e2dc563eb1e8.png)

![image](https://cloud.githubusercontent.com/assets/3836616/23191873/fd0a8f74-f854-11e6-8f59-03c18ec15a3c.png)

Behavior is noticed in app with default color options and shared theme/custom color options

**Comment by allisonmuise** [comment]
closing - app will be moved to mature support at 6.1. Use Minimal Gallery app instead.
