### ISSUE TITLE
Group description is cut off Maps and Apps Gallery

### ISSUE THREAD

**Issue by beromero** [Esri/map-and-app-gallery-template#219]
The group description is not fully visible when expanded.  When the window is resized a scroll bar appears but still does enable all the text to be displayed.  This issue occurs when the text exceeds the length of the length of the browser window. This issue occurs in IE, firefox, and chrome. it's most apparent in Chrome. 
![image](https://cloud.githubusercontent.com/assets/9092525/26372243/79beee1e-3fba-11e7-926b-3f4267fccb9c.png)
 
Example Gallery: https://sharedtheme.maps.arcgis.com/apps/MapAndAppGallery/index.html?appid=dde4717a64844db8b57815cdef11f871

**Comment by allisonmuise** [comment]
closing - app will be moved to mature support at 6.1. Use Minimal Gallery app instead.
