### ISSUE TITLE
Re-assess shared theme on mobile devices

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#221]

**Comment by allisonmuise** [comment]
shared theme colors are being applied to the mobile view of the app header in such a way that the title is hard to read.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

In the current implementation for mobile view selected theme color is used to show text in app header, and the background is always white.

![image](https://user-images.githubusercontent.com/2959186/28704771-27d4329a-738a-11e7-9bba-5897ef8bf6de.png)

Please let us know what changes you would like to implement in this.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam My apologies, I meant to add more detail to this issue.

The problem is when the configured color is white. Under these circumstances, the header becomes white text on a white background when in mobile mode, even though desktop mode handles it.
http://arcgis4localgov2.maps.arcgis.com/apps/MapAndAppGallery/index.html?appid=72b5fbeb7ce74f1f966527a97e01c3c1

**Comment by CTLocalGovTeam** [comment]
@allisonmuise,

We have fixed this issue and below is the output after executing an application.

_**Windows 7 - Chrome:**_
![image](https://user-images.githubusercontent.com/2959186/28960690-4a5c6132-791d-11e7-8755-d7cdb80ec16b.png)

_**Mobile Device:**_
![image](https://user-images.githubusercontent.com/2959186/28960662-2ab19582-791d-11e7-8c0d-26b92c64b0fa.png)

This fix will be available in the upcoming code drop.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam Yes, please make this additional change. Thanks for catching this!

**Comment by allisonmuise** [comment]
verified on devext
