### ISSUE TITLE
 DojoConfig: Update apps to set async:true to avoid console warning

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#226]
In apps that create a web map the following warning appears in the console unless dojoConfig async is set to true.

[Deprecation] Synchronous XMLHttpRequest on the main thread is deprecated because of its detrimental effects to the end user's experience.

Set to true in config apps to remove this warning (and the associated problems it warns about) from the app.

**Comment by allisonmuise** [comment]
1649

**Comment by CTLocalGovTeam** [comment]
@allisonmuise 

We are not able to see any warnings in console. 

The dojoConfig async parameter is already being set to 'true' in [dojoConfiguration.js](https://github.com/Esri/map-and-app-gallery-template/blob/master/coreLibrary/dojoConfiguration.js#L25) file.

Could you please correct if we are missing anything.

**Comment by allisonmuise** [comment]
@CTLocalGovTeam : Thanks for checking. I will close as this issue does not appear to apply to this app.
