### ISSUE TITLE
App fails to load if the sort type is number of views

### ISSUE THREAD

**Issue by skrishn** [Esri/map-and-app-gallery-template#231]
Noticed in dev env, if the items are sorted by ‘number of views’ it errors out. No issues if sorted by ‘date’ or ‘name’ .

This is due to the elastic search upgrade in the back-end.

**Comment by allisonmuise** [comment]
@skrishn Is this a regression?

**Comment by skrishn** [comment]
@allisonmuise : Yes. AGOL team is working on it - `[its ](https://devtopia.esri.com/WebGIS/arcgis-portal-qa/issues/100#issuecomment-850181)not specific to map and app gallery.

**Comment by allisonmuise** [comment]
@skrishn  - I'm closing this as there are issues in devtopia monitoring this behavior, and it's not specific to this app.
