### ISSUE TITLE
Add UI ability to change sort order

### ISSUE THREAD

**Issue by allisonmuise** [Esri/map-and-app-gallery-template#70]
Currently ascending/descending sort order can only be set in the config. This should be accessible in the UI
(via Matt Driscoll)

**Comment by allisonmuise** [comment]
Current Sort By:
![sortby](https://cloud.githubusercontent.com/assets/2752195/6672771/d1d7f3b2-cbcb-11e4-8792-9e82c5b5efdd.png)

Proposed Sort Order:
![sortorder](https://cloud.githubusercontent.com/assets/2752195/6672773/d806970c-cbcb-11e4-8e85-0e05db5813e8.png)

Any of the Sort By options should work with either of the Sort Order options

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We suggest either of the following 2 options:
Option 1-
![opt-1](https://cloud.githubusercontent.com/assets/2959186/7176502/a7cf0eaa-e43c-11e4-8b26-f16718103b38.png)

Option 2-
![opt-2](https://cloud.githubusercontent.com/assets/2959186/7176507/b3844378-e43c-11e4-9c73-e37028f85199.png)

Please confirm if we need to implement UI as per the screenshot given by you or as given in Option 1 or 2.

**Comment by allisonmuise** [comment]
Per the conversation this morning, please proceed with Option 1

**Comment by CTLocalGovTeam** [comment]
@allisonmuise We will implement option 1 and include the changes in next release.

**Comment by CTLocalGovTeam** [comment]
@allisonmuise For smartphones, we suggest below UI options. Could you please confirm one of those?

Option 1
![image](https://cloud.githubusercontent.com/assets/2959186/7273578/ba5d29e6-e912-11e4-866b-36b7ee5192ee.png)


Option 2
![image](https://cloud.githubusercontent.com/assets/2959186/7273588/c752a57c-e912-11e4-9aff-601a2643360d.png)


Option 3
![image](https://cloud.githubusercontent.com/assets/2959186/7273589/cb78ab10-e912-11e4-8eb9-58b82b61c78e.png)

**Comment by allisonmuise** [comment]
Let's go with Option 3

**Comment by allisonmuise** [comment]
verified
