### ISSUE TITLE
Focus is displayed beyond the tittle in the header panel.

### ISSUE THREAD

**Issue by CTLocalGovTeam** [Esri/map-and-app-gallery-template#99]
1. Launch the application.
2. Tap on thumbnail of any Feature Service/ Map Service item.
3. Tap on the title in the header panel.
4. Observed that the focus is displayed beyond the title.

![focus](https://cloud.githubusercontent.com/assets/2959186/3838071/9f56ec36-1dfc-11e4-82e5-7528fe6d91c1.png)

**Comment by allisonmuise** [comment]
marking this as known issue and closing as it does not impact app functionality
